---
# Ansible sample playbook
- hosts: all

  sudo: yes

  tasks:
  - name: Install the Extra Packages for Enterprise Linux (EPEL)
    yum: name={{ item }} state=installed
    with_items: epel-release
    when: ansible_os_family == 'RedHat'